import { contextBridge, ipcRenderer } from "electron";
import type { MaterialEmailApi } from "../shared/contracts.js";

const api: MaterialEmailApi = {
  onMailto: callback => {
    const listener = (_event: Electron.IpcRendererEvent, url: string) => callback(url);
    ipcRenderer.on("app:mailto", listener);
    return () => ipcRenderer.removeListener("app:mailto", listener);
  },
  bootstrap: () => ipcRenderer.invoke("app:bootstrap"),
  chooseAttachments: () => ipcRenderer.invoke("dialog:attachments"),
  createDemoAccount: () => ipcRenderer.invoke("account:create-demo"),
  discoverAccount: email => ipcRenderer.invoke("account:discover", email),
  addAccount: draft => ipcRenderer.invoke("account:add", draft),
  testAccount: draft => ipcRenderer.invoke("account:test", draft),
  removeAccount: accountId => ipcRenderer.invoke("account:remove", accountId),
  syncAccount: accountId => ipcRenderer.invoke("mail:sync", accountId),
  listFolders: accountId => ipcRenderer.invoke("mail:folders", accountId),
  listMessages: (accountId, folderPath) => ipcRenderer.invoke("mail:messages", accountId, folderPath),
  getMessage: (accountId, folderPath, uid) => ipcRenderer.invoke("mail:message", accountId, folderPath, uid),
  saveAttachment: (accountId, folderPath, uid, index) => ipcRenderer.invoke("mail:save-attachment", accountId, folderPath, uid, index),
  saveAllAttachments: (accountId, folderPath, uid) => ipcRenderer.invoke("mail:save-all-attachments", accountId, folderPath, uid),
  setMessageFlags: (accountId, folderPath, uid, patch) => ipcRenderer.invoke("mail:flags", accountId, folderPath, uid, patch),
  moveMessage: (accountId, folderPath, uid, destination) => ipcRenderer.invoke("mail:move", accountId, folderPath, uid, destination),
  sendMessage: draft => ipcRenderer.invoke("mail:send", draft),
  saveDraft: draft => ipcRenderer.invoke("mail:save-draft", draft),
  listDrafts: accountId => ipcRenderer.invoke("mail:drafts", accountId),
  getDraft: (accountId, draftId) => ipcRenderer.invoke("mail:draft", accountId, draftId),
  deleteDraft: (accountId, draftId) => ipcRenderer.invoke("mail:delete-draft", accountId, draftId),
  listOutbox: accountId => ipcRenderer.invoke("mail:outbox", accountId),
  cancelOutbox: (accountId, outboxId) => ipcRenderer.invoke("mail:cancel-outbox", accountId, outboxId),
  retryOutbox: (accountId, outboxId) => ipcRenderer.invoke("mail:retry-outbox", accountId, outboxId),
  savePreferences: patch => ipcRenderer.invoke("preferences:save", patch),
  markNotificationRead: (id, read) => ipcRenderer.invoke("notifications:read", id, read),
  clearNotifications: () => ipcRenderer.invoke("notifications:clear"),
  restoreHistory: id => ipcRenderer.invoke("history:restore", id),
  listLocalRevisions: () => ipcRenderer.invoke("history:list-local"),
  restoreLocalRevision: hash => ipcRenderer.invoke("history:restore-local", hash),
  listContacts: () => ipcRenderer.invoke("pim:contacts:list"),
  searchContacts: query => ipcRenderer.invoke("pim:contacts:search", query),
  createContact: input => ipcRenderer.invoke("pim:contacts:create", input),
  updateContact: (uid, patch) => ipcRenderer.invoke("pim:contacts:update", uid, patch),
  deleteContact: uid => ipcRenderer.invoke("pim:contacts:delete", uid),
  restoreContact: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:contacts:restore", uid, sourceTransactionId),
  importVCard: () => ipcRenderer.invoke("pim:vcard:import"),
  exportVCard: (contactUids, mailingListUids) => ipcRenderer.invoke("pim:vcard:export", contactUids, mailingListUids),
  listMailingLists: () => ipcRenderer.invoke("pim:mailing-lists:list"),
  listMailingListMembers: uid => ipcRenderer.invoke("pim:mailing-lists:members", uid),
  createMailingList: input => ipcRenderer.invoke("pim:mailing-lists:create", input),
  updateMailingList: (uid, patch) => ipcRenderer.invoke("pim:mailing-lists:update", uid, patch),
  deleteMailingList: uid => ipcRenderer.invoke("pim:mailing-lists:delete", uid),
  restoreMailingList: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:mailing-lists:restore", uid, sourceTransactionId),
  listCalendarEvents: () => ipcRenderer.invoke("pim:events:list"),
  createCalendarEvent: input => ipcRenderer.invoke("pim:events:create", input),
  updateCalendarEvent: (uid, patch) => ipcRenderer.invoke("pim:events:update", uid, patch),
  deleteCalendarEvent: uid => ipcRenderer.invoke("pim:events:delete", uid),
  restoreCalendarEvent: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:events:restore", uid, sourceTransactionId),
  listTasks: () => ipcRenderer.invoke("pim:tasks:list"),
  createTask: input => ipcRenderer.invoke("pim:tasks:create", input),
  updateTask: (uid, patch) => ipcRenderer.invoke("pim:tasks:update", uid, patch),
  deleteTask: uid => ipcRenderer.invoke("pim:tasks:delete", uid),
  restoreTask: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:tasks:restore", uid, sourceTransactionId),
  listPimTransactions: filter => ipcRenderer.invoke("pim:transactions:list", filter),
  exportData: (kind, content, suggestedName) => ipcRenderer.invoke("data:export", kind, content, suggestedName),
  detectEditors: () => ipcRenderer.invoke("editor:detect"),
  openExternalEditor: editorPath => ipcRenderer.invoke("editor:open", editorPath),
  minimize: () => ipcRenderer.invoke("window:minimize"),
  maximize: () => ipcRenderer.invoke("window:maximize"),
  close: () => ipcRenderer.invoke("window:close"),
};

contextBridge.exposeInMainWorld("materialEmail", Object.freeze(api));
