import { contextBridge, ipcRenderer } from "electron";
import type { MaterialEmailApi } from "../shared/contracts.js";

const api: MaterialEmailApi = {
  onMailto: callback => {
    const listener = (_event: Electron.IpcRendererEvent, url: string) => callback(url);
    ipcRenderer.on("app:mailto", listener);
    return () => ipcRenderer.removeListener("app:mailto", listener);
  },
  onExternalLinkReview: callback => {
    const listener = (_event: Electron.IpcRendererEvent, request: Parameters<typeof callback>[0]) => callback(request);
    ipcRenderer.on("external-link:review", listener);
    return () => ipcRenderer.removeListener("external-link:review", listener);
  },
  confirmExternalLink: requestId => ipcRenderer.invoke("external-link:confirm", requestId),
  cancelExternalLink: requestId => ipcRenderer.invoke("external-link:cancel", requestId),
  bootstrap: () => ipcRenderer.invoke("app:bootstrap"),
  chooseAttachments: () => ipcRenderer.invoke("dialog:attachments"),
  createDemoAccount: () => ipcRenderer.invoke("account:create-demo"),
  discoverAccount: email => ipcRenderer.invoke("account:discover", email),
  getOAuthAuthorizationStatus: () => ipcRenderer.invoke("account:oauth-status"),
  startOAuthAuthorization: provider => ipcRenderer.invoke("account:oauth-start", provider),
  cancelOAuthAuthorization: () => ipcRenderer.invoke("account:oauth-cancel"),
  getOAuthSignInStatus: () => ipcRenderer.invoke("account:oauth-signin-status"),
  getOAuthTokenVaultStatus: () => ipcRenderer.invoke("account:oauth-vault-status"),
  clearOAuthTokenVault: provider => ipcRenderer.invoke("account:oauth-vault-clear", provider),
  revokeOAuthTokenVault: provider => ipcRenderer.invoke("account:oauth-vault-revoke", provider),
  inspectTlsCertificate: request => ipcRenderer.invoke("account:inspect-tls-certificate", request),
  cancelPop3AccountTest: () => ipcRenderer.invoke("account:pop3-test-cancel"),
  runPimProviderFoundation: profile => ipcRenderer.invoke("pim:provider-foundation", profile),
  addAccount: draft => ipcRenderer.invoke("account:add", draft),
  testAccount: draft => ipcRenderer.invoke("account:test", draft),
  removeAccount: accountId => ipcRenderer.invoke("account:remove", accountId),
  syncAccount: accountId => ipcRenderer.invoke("mail:sync", accountId),
  listFolders: accountId => ipcRenderer.invoke("mail:folders", accountId),
  listMessages: (accountId, folderPath) => ipcRenderer.invoke("mail:messages", accountId, folderPath),
  listUnifiedMessages: folder => ipcRenderer.invoke("mail:unified-messages", folder),
  searchCachedMail: query => ipcRenderer.invoke("mail:search-cached", query),
  getMessage: (accountId, folderPath, uid) => ipcRenderer.invoke("mail:message", accountId, folderPath, uid),
  setRemoteContentAllowed: (accountId, folderPath, uid, allowed) => ipcRenderer.invoke("mail:remote-content", accountId, folderPath, uid, allowed),
  saveAttachment: (accountId, folderPath, uid, index, review) => review
    ? ipcRenderer.invoke("mail:save-attachment", accountId, folderPath, uid, index, review)
    : ipcRenderer.invoke("mail:save-attachment", accountId, folderPath, uid, index),
  saveAllAttachments: (accountId, folderPath, uid, review) => review
    ? ipcRenderer.invoke("mail:save-all-attachments", accountId, folderPath, uid, review)
    : ipcRenderer.invoke("mail:save-all-attachments", accountId, folderPath, uid),
  releaseQuarantinedAttachment: id => ipcRenderer.invoke("quarantine:release", id),
  deleteQuarantinedAttachment: id => ipcRenderer.invoke("quarantine:delete", id),
  setMessageFlags: (accountId, folderPath, uid, patch) => ipcRenderer.invoke("mail:flags", accountId, folderPath, uid, patch),
  moveMessage: (accountId, folderPath, uid, destination) => ipcRenderer.invoke("mail:move", accountId, folderPath, uid, destination),
  createFolder: (accountId, folderPath) => ipcRenderer.invoke("mail:create-folder", accountId, folderPath),
  renameFolder: (accountId, folderPath, name) => ipcRenderer.invoke("mail:rename-folder", accountId, folderPath, name),
  deleteFolder: (accountId, folderPath) => ipcRenderer.invoke("mail:delete-folder", accountId, folderPath),
  markFolderRead: (accountId, folderPath) => ipcRenderer.invoke("mail:mark-folder-read", accountId, folderPath),
  listIdentities: () => ipcRenderer.invoke("identities:list"),
  saveIdentity: input => ipcRenderer.invoke("identities:save", input),
  deleteIdentity: id => ipcRenderer.invoke("identities:delete", id),
  setDefaultIdentity: id => ipcRenderer.invoke("identities:default", id),
  listMessageTags: () => ipcRenderer.invoke("tags:list"),
  listMessageTagAssignments: () => ipcRenderer.invoke("tags:assignments"),
  createMessageTag: (name, colour) => ipcRenderer.invoke("tags:create", name, colour),
  updateMessageTag: (id, patch) => ipcRenderer.invoke("tags:update", id, patch),
  deleteMessageTag: id => ipcRenderer.invoke("tags:delete", id),
  setMessageTags: (accountId, folderPath, uid, tagIds) => ipcRenderer.invoke("tags:set", accountId, folderPath, uid, tagIds),
  listMessageFilters: () => ipcRenderer.invoke("filters:list"),
  saveMessageFilter: input => ipcRenderer.invoke("filters:save", input),
  deleteMessageFilter: id => ipcRenderer.invoke("filters:delete", id),
  reorderMessageFilters: orderedIds => ipcRenderer.invoke("filters:reorder", orderedIds),
  previewMessageFilterRun: (accountId, folderPath) => ipcRenderer.invoke("filters:preview", accountId, folderPath),
  runMessageFilters: (accountId, folderPath) => ipcRenderer.invoke("filters:run", accountId, folderPath),
  getJunkSummary: () => ipcRenderer.invoke("junk:summary"),
  classifyMessageJunk: (accountId, folderPath, uid) => ipcRenderer.invoke("junk:classify", accountId, folderPath, uid),
  trainMessageJunk: (accountId, folderPath, uid, label) => ipcRenderer.invoke("junk:train", accountId, folderPath, uid, label),
  resetJunkModel: () => ipcRenderer.invoke("junk:reset"),
  sendMessage: draft => ipcRenderer.invoke("mail:send", draft),
  saveDraft: draft => ipcRenderer.invoke("mail:save-draft", draft),
  listDrafts: accountId => ipcRenderer.invoke("mail:drafts", accountId),
  getDraft: (accountId, draftId) => ipcRenderer.invoke("mail:draft", accountId, draftId),
  deleteDraft: (accountId, draftId) => ipcRenderer.invoke("mail:delete-draft", accountId, draftId),
  listPendingOperations: accountId => ipcRenderer.invoke("mail:pending-operations", accountId),
  retryPendingOperation: (accountId, operationId) => ipcRenderer.invoke("mail:retry-pending-operation", accountId, operationId),
  discardPendingOperation: (accountId, operationId) => ipcRenderer.invoke("mail:discard-pending-operation", accountId, operationId),
  listOutbox: accountId => ipcRenderer.invoke("mail:outbox", accountId),
  cancelOutbox: (accountId, outboxId) => ipcRenderer.invoke("mail:cancel-outbox", accountId, outboxId),
  retryOutbox: (accountId, outboxId) => ipcRenderer.invoke("mail:retry-outbox", accountId, outboxId),
  savePreferences: patch => ipcRenderer.invoke("preferences:save", patch),
  markNotificationRead: (id, read) => ipcRenderer.invoke("notifications:read", id, read),
  markNotificationDismissed: (id, dismissed) => ipcRenderer.invoke("notifications:dismissed", id, dismissed),
  clearNotifications: () => ipcRenderer.invoke("notifications:clear"),
  nativeNotification: kind => ipcRenderer.invoke("notifications:native", kind),
  restoreHistory: id => ipcRenderer.invoke("history:restore", id),
  listLocalRevisions: () => ipcRenderer.invoke("history:list-local"),
  getLocalRevisionDiff: hash => ipcRenderer.invoke("history:diff-local", hash),
  labelLocalRevision: (hash, label) => ipcRenderer.invoke("history:label-local", hash, label),
  previewLocalHistoryPrune: retentionDays => ipcRenderer.invoke("history:preview-prune-local", retentionDays),
  pruneLocalHistory: request => ipcRenderer.invoke("history:prune-local", request),
  inspectLocalHistoryDeletion: () => ipcRenderer.invoke("history:inspect-deletion"),
  restoreLocalRevision: hash => ipcRenderer.invoke("history:restore-local", hash),
  listContacts: () => ipcRenderer.invoke("pim:contacts:list"),
  searchContacts: query => ipcRenderer.invoke("pim:contacts:search", query),
  createContact: input => ipcRenderer.invoke("pim:contacts:create", input),
  updateContact: (uid, patch) => ipcRenderer.invoke("pim:contacts:update", uid, patch),
  deleteContact: uid => ipcRenderer.invoke("pim:contacts:delete", uid),
  restoreContact: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:contacts:restore", uid, sourceTransactionId),
  importVCard: () => ipcRenderer.invoke("pim:vcard:import"),
  exportVCard: (contactUids, mailingListUids) => ipcRenderer.invoke("pim:vcard:export", contactUids, mailingListUids),
  importICalendar: duplicatePolicy => ipcRenderer.invoke("pim:ics:import", duplicatePolicy),
  exportICalendar: request => ipcRenderer.invoke("pim:ics:export", request),
  listMailingLists: () => ipcRenderer.invoke("pim:mailing-lists:list"),
  listMailingListMembers: uid => ipcRenderer.invoke("pim:mailing-lists:members", uid),
  createMailingList: input => ipcRenderer.invoke("pim:mailing-lists:create", input),
  updateMailingList: (uid, patch) => ipcRenderer.invoke("pim:mailing-lists:update", uid, patch),
  deleteMailingList: uid => ipcRenderer.invoke("pim:mailing-lists:delete", uid),
  restoreMailingList: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:mailing-lists:restore", uid, sourceTransactionId),
  listCalendarEvents: () => ipcRenderer.invoke("pim:events:list"),
  createCalendarEvent: input => ipcRenderer.invoke("pim:events:create", input),
  updateCalendarEvent: (uid, patch) => ipcRenderer.invoke("pim:events:update", uid, patch),
  deleteCalendarEvent: uid => ipcRenderer.invoke("pim:events:delete", uid),
  restoreCalendarEvent: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:events:restore", uid, sourceTransactionId),
  listTasks: () => ipcRenderer.invoke("pim:tasks:list"),
  createTask: input => ipcRenderer.invoke("pim:tasks:create", input),
  updateTask: (uid, patch) => ipcRenderer.invoke("pim:tasks:update", uid, patch),
  deleteTask: uid => ipcRenderer.invoke("pim:tasks:delete", uid),
  restoreTask: (uid, sourceTransactionId) => ipcRenderer.invoke("pim:tasks:restore", uid, sourceTransactionId),
  listPimTransactions: filter => ipcRenderer.invoke("pim:transactions:list", filter),
  exportData: (kind, content, suggestedName) => ipcRenderer.invoke("data:export", kind, content, suggestedName),
  exportTabAppearanceTheme: theme => ipcRenderer.invoke("appearance-theme:export", theme),
  importTabAppearanceTheme: () => ipcRenderer.invoke("appearance-theme:import"),
  detectEditors: () => ipcRenderer.invoke("editor:detect"),
  openExternalEditor: editorPath => ipcRenderer.invoke("editor:open", editorPath),
  getWindowState: () => ipcRenderer.invoke("window:state"),
  onWindowStateChanged: callback => {
    const listener = (_event: Electron.IpcRendererEvent, state: Parameters<typeof callback>[0]) => callback(state);
    ipcRenderer.on("window:state-changed", listener);
    return () => ipcRenderer.removeListener("window:state-changed", listener);
  },
  onWindowCloseRequested: callback => {
    const listener = () => callback();
    ipcRenderer.on("window:close-requested", listener);
    return () => ipcRenderer.removeListener("window:close-requested", listener);
  },
  minimize: () => ipcRenderer.invoke("window:minimize"),
  maximize: () => ipcRenderer.invoke("window:maximize"),
  close: () => ipcRenderer.invoke("window:close"),
};

contextBridge.exposeInMainWorld("materialEmail", Object.freeze(api));
